return {
	-- 	{
	-- 		"mfussenegger/nvim-lint",
	-- 		events = { "BufWritePost", "BufReadPost", "InsertLeave" },
	-- 		config = function()
	-- 			local lint = require("lint")
	-- 			lint.linters_by_file = {
	-- 				javascript = { "eslint_d" },
	-- 				typescript = { "eslint_d" },
	-- 				javascriptreact = { "eslint_d" },
	-- 				typescriptreact = { "eslint_d" },
	-- 				gitcommit = { "gitlint" },
	-- 			}
	--
	-- 			local lint_augroup = vim.api.nvim_create_augroup("lint", {
	-- 				clear = true,
	-- 			})
	--
	-- 			vim.api.nvim_create_autocmd({
	-- 				"BufEnter",
	-- 				"BufWritePost",
	-- 				"InsertLeave",
	-- 			}, {
	-- 				group = lint_augroup,
	-- 				callback = function()
	-- 					lint.try_lint()
	-- 				end,
	-- 			})
	--
	-- 			vim.keymap.set("n", "<leader>l", function()
	-- 				lint.try_lint()
	-- 			end, { desc = "Trigger linting current file" })
	-- 		end,
	-- 	},
}
